### ISSUE TITLE
SD-Model null/undefined. Installing everything was fine on Window 11 (Fresh ComfyUI 3.11).

### ISSUE THREAD

**Issue by AImmd** [AIFSH/ComfyUI-Hallo#13]
![image](https://github.com/AIFSH/ComfyUI-Hallo/assets/135707290/6d288721-0b97-460d-aaa8-56a59c8b5230)

I dont know if thats a bug or intended, but i tried a 30 second Audio and it takes more than 25 min, just iterate throw.
Does it need that much time or is this caused by the SD Model undefined or this error Message before generating (triton)?

---------------------------------------------------------------------------------------------------------------------------------

E:\ComfyUI_LipSync>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build  --listen 0.0.0.0
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-20 11:04:21.560366
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: E:\ComfyUI_LipSync\python_embeded\python.exe
** Log path: E:\ComfyUI_LipSync\comfyui.log

Prestartup times for custom nodes:
   1.1 seconds: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 32688 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
!!!Hallo path was added to E:\ComfyUI_LipSync\python_embeded\Lib\site-packages/Hallo.pth
 if meet No module named 'hallo' error,please restart comfyui
Hallo use cache models,make sure your 'pretrained_models' complete
E:\ComfyUI_LipSync\python_embeded\Lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models
### ComfyUI Revision: 2244 [c8b5e08d] | Released on '2024-06-12'

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.3 seconds: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Manager
   3.7 seconds: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo

Starting server

To see the GUI go to: http://0.0.0.0:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
FETCH DATA from: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
 [DONE]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
FETCH DATA from: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\stable-diffusion-v1-5
E:\ComfyUI_LipSync\python_embeded\python.exe E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py --config "E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\tmp.yaml" --source_image "E:\ComfyUI_LipSync\ComfyUI\input\Screenshot 2024-06-20 110451.png" --driving_audio "E:\ComfyUI_LipSync\ComfyUI\input\e710c1cbb8997b6952152af7dd9c0558.wav" --output E:\ComfyUI_LipSync\ComfyUI\output\hallo_1718874316574483100.mp4 --pose_weight 1.0 --face_weight 1.0 --lip_weight 1.0 --face_expand_ratio 1.2
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "E:\ComfyUI_LipSync\python_embeded\Lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_LipSync\python_embeded\Lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
E:\ComfyUI_LipSync\python_embeded\Lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
WARNING:py.warnings:E:\ComfyUI_LipSync\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\face_analysis\models\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\face_analysis\models\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\face_analysis\models\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\face_analysis\models\glintr100.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\face_analysis\models\scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
WARNING:py.warnings:E:\ComfyUI_LipSync\python_embeded\Lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1718874323.341939   10752 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1718874323.349443   22496 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1718874323.357586   24524 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
WARNING:py.warnings:E:\ComfyUI_LipSync\python_embeded\Lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '

Processed and saved: E:\ComfyUI_LipSync\ComfyUI\output\hallo\Screenshot 2024-06-20 110451_sep_background.png
Processed and saved: E:\ComfyUI_LipSync\ComfyUI\output\hallo\Screenshot 2024-06-20 110451_sep_face.png
Some weights of Wav2VecModel were not initialized from the model checkpoint at E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\wav2vec\wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
INFO:audio_separator.separator.separator:Separator version 0.17.4 instantiating with output_dir: E:\ComfyUI_LipSync\ComfyUI\output\hallo\audio_preprocess, output_format: WAV
INFO:audio_separator.separator.separator:Operating System: Windows 10.0.22631
INFO:audio_separator.separator.separator:System: Windows Node: Sophon Release: 10 Machine: AMD64 Proc: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
INFO:audio_separator.separator.separator:Python Version: 3.11.8
INFO:audio_separator.separator.separator:PyTorch Version: 2.3.0+cu121
INFO:audio_separator.separator.separator:FFmpeg installed: ffmpeg version 2024-06-06-git-d55f5cba7b-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
INFO:audio_separator.separator.separator:ONNX Runtime CPU package installed with version: 1.18.0
INFO:audio_separator.separator.separator:CUDA is available in Torch, setting Torch device to CUDA
WARNING:audio_separator.separator.separator:CUDAExecutionProvider not available in ONNXruntime, so acceleration will NOT be enabled
INFO:audio_separator.separator.separator:Loading model Kim_Vocal_2.onnx...
INFO:audio_separator.separator.separator:Load model duration: 00:00:00
INFO:audio_separator.separator.separator:Starting separation process for audio_file_path: E:\ComfyUI_LipSync\ComfyUI\input\e710c1cbb8997b6952152af7dd9c0558.wav
100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:16<00:00,  2.76s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 13.32it/s]
INFO:audio_separator.separator.separator:Saving Vocals stem to e710c1cbb8997b6952152af7dd9c0558_(Vocals)_Kim_Vocal_2.wav...
INFO:audio_separator.separator.separator:Clearing input audio file paths, sources and stems...
INFO:audio_separator.separator.separator:Separation duration: 00:00:17
The config attributes {'center_input_sample': False, 'out_channels': 4} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel:
 ['conv_norm_out.bias, conv_norm_out.weight, conv_out.bias, conv_out.weight']
INFO:hallo.models.unet_3d:loaded temporal unet's pretrained weights from E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\stable-diffusion-v1-5\unet ...
The config attributes {'center_input_sample': False} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Load motion module params from E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\motion_module\mm_sd_v15_v2.ckpt
INFO:hallo.models.unet_3d:Loaded 453.20928M-parameter motion module
loaded weight from  E:\ComfyUI_LipSync\ComfyUI\custom_nodes\ComfyUI-Hallo\pretrained_models\hallo\net.pth
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [01:05<00:00,  1.63s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 17.32it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [01:03<00:00,  1.60s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 17.65it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [01:03<00:00,  1.59s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 18.00it/s]
 95%|█████████████████████████████████████████████████████████████████████████████▉    | 38/40 [01:00<00:03,  1.62s/it]

**Comment by AIFSH** [comment]
wait patiently till video finish generated
