### ISSUE TITLE
 cannot run with `cpu` device.

### ISSUE THREAD

**Issue by Neo-Pz** [AIFSH/ComfyUI-Hallo#19]
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.

**Comment by AIFSH** [comment]
no way to CPU，as too slow even on GPU
