### ISSUE TITLE
can you help this out?

### ISSUE THREAD

**Issue by muwaaaah** [AIFSH/ComfyUI-Hallo#23]
**C:\ComfyUI_windows_portable\python_embeded>python.exe -m pip install -r requirements.txt**

Collecting diffusers (from -r requirements.txt (line 1))
  Using cached diffusers-0.29.1-py3-none-any.whl.metadata (19 kB)
Collecting omegaconf (from -r requirements.txt (line 2))
  Using cached omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting librosa (from -r requirements.txt (line 3))
  Using cached librosa-0.10.2.post1-py3-none-any.whl.metadata (8.6 kB)
Collecting audio-separator (from -r requirements.txt (line 4))
  Using cached audio_separator-0.17.4-py3-none-any.whl.metadata (23 kB)
Collecting onnxruntime (from -r requirements.txt (line 5))
  Using cached onnxruntime-1.18.0-cp311-cp311-win_amd64.whl.metadata (4.4 kB)
Collecting opencv-python (from -r requirements.txt (line 6))
  Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting onnx2torch (from -r requirements.txt (line 7))
  Using cached onnx2torch-1.5.14-py3-none-any.whl.metadata (23 kB)
Collecting onnx (from -r requirements.txt (line 8))
  Using cached onnx-1.16.1-cp311-cp311-win_amd64.whl.metadata (16 kB)
Collecting moviepy (from -r requirements.txt (line 9))
  Using cached moviepy-1.0.3-py3-none-any.whl
Requirement already satisfied: accelerate in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 10)) (0.31.0)
Collecting av (from -r requirements.txt (line 11))
  Using cached av-12.1.0-cp311-cp311-win_amd64.whl.metadata (4.7 kB)
Collecting bitsandbytes (from -r requirements.txt (line 12))
  Using cached bitsandbytes-0.43.1-py3-none-win_amd64.whl.metadata (2.2 kB)
Collecting decord (from -r requirements.txt (line 13))
  Using cached decord-0.6.0-py3-none-win_amd64.whl.metadata (422 bytes)
Requirement already satisfied: einops in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 14)) (0.8.0)

_**Below error**_

Collecting insightface (from -r requirements.txt (line 15))
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\ComfyUI_windows_portable\python_embeded>

**Comment by muwaaaah** [comment]
C:\ComfyUI_windows_portable\python_embeded>python.exe -m pip list
Package            Version
------------------ ------------
accelerate         0.31.0
aiohttp            3.9.5
aiosignal          1.3.1
attrs              23.2.0
certifi            2024.6.2
cffi               1.16.0
charset-normalizer 3.3.2
colorama           0.4.6
einops             0.8.0
ffmpeg             1.4
filelock           3.15.1
frozenlist         1.4.1
fsspec             2024.6.0
huggingface-hub    0.23.4
idna               3.7
intel-openmp       2021.4.0
Jinja2             3.1.4
kornia             0.7.2
kornia_rs          0.1.3
MarkupSafe         2.1.5
mkl                2021.4.0
mpmath             1.3.0
multidict          6.0.5
networkx           3.3
numpy              1.26.4
packaging          24.1
pillow             10.3.0
pip                24.1
psutil             5.9.8
pycparser          2.22
pygit2             1.15.0
PyYAML             6.0.1
regex              2024.5.15
requests           2.32.3
safetensors        0.4.3
scipy              1.13.1
setuptools         70.0.0
soundfile          0.12.1
spandrel           0.3.4
sympy              1.12.1
tbb                2021.12.0
tokenizers         0.19.1
torch              2.1.0+cu121
torchaudio         2.1.0+cu121
torchsde           0.2.6
torchvision        0.16.0+cu121
tqdm               4.66.4
trampoline         0.1.2
transformers       4.41.2
typing_extensions  4.12.2
urllib3            2.2.2
wheel              0.43.0
xformers           0.0.22.post7
yarl               1.9.4

**Comment by muwaaaah** [comment]
I also installed Visual Studio Build Tools 2022 
 -  C++ desktop development (++win 11 SDK)

**Comment by AIFSH** [comment]
py310
