### ISSUE TITLE
ModuleNotFoundError: No module named 'triton'

### ISSUE THREAD

**Issue by ping3839** [AIFSH/ComfyUI-Hallo#5]
Has anyone else encountered this? What's the solution?

**Comment by Mikerhinos** [comment]
This shouldn't be a problem, I also have it, and I have it on other tools that are still working.

**Comment by ping3839** [comment]
Mine won't work.

**Comment by Mikerhinos** [comment]
Are you sure you don't have this error just after ?

https://github.com/AIFSH/ComfyUI-Hallo/issues/2

**Comment by pneumanon** [comment]
I have the same error followed by ModuleNotFoundError: No module named 'diffusers.models.transformers'
