### ISSUE TITLE
[SUGESTION] Expose model and inference parameters as inputs

### ISSUE THREAD

**Issue by marianbasti** [AIFSH/ComfyUI-Hallo#8]
Thanks for this cool contribution!

From the original repo, I can see that it uses SD1.5 for generating the faces

It would be interesting to be able to set any arbitrary model and experiment the possibilities that different models can do, in terms of quality and speed

**Comment by AIFSH** [comment]
good，i will try to do that

**Comment by marianbasti** [comment]
[This](https://github.com/fudan-generative-vision/hallo/blob/f7379b4f64d0793e515e6feaeec832f68d4a039a/scripts/inference.py#L197) is the line that loads the unet, and a couple of lines before, the motion module (I also noted that the motion model is v2, an older one).

Im thinking there's 2 options, either have a model and motion model as separate inputs, or only having a single model input with the motion model already applied (i think the latter is better).

**Comment by AIFSH** [comment]
i give a optional input for sd_model but only support diffusers file type by now
